### PR TITLE
Added new quotes

### PR DESCRIPTION
**Pull request by ganeshhubale**
Following are the authors of quotes:
1. Ken Thompson
2. Richard Stallman
3. Larry Ellison
4. Paul Allen
5. Dennis Ritchie

Source: google

### CODE REVIEW

**Comment by mubaris** [comment]
Create a new file. Do not edit

**Comment by ganeshhubale** [comment]
@mubaris 
As i understood,
I need to create new file with quotes here - **motivate/motivate/data/newfile.json**

**Comment by mubaris** [comment]
you need to create a new numbered file. check the repo structure

**Comment by ganeshhubale** [comment]
@mubaris 
Yes, I went through repo structure and made modified PR.
Take a look at it.
https://github.com/mubaris/motivate/pull/164/commits/b9947c1841e98d4972de3eb0128741e3d1a48e2a

**Pull request merged**
